name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: actions/cache@v1
      with:
        path: .vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Setup bundler
      run: |
        gem install bundler
        bundle config path .vendor/bundle
        bundle config set without 'system_tests development release'
        bundle install --jobs 4 --retry 3
    - name: execute puppet-lint
      run: bundle exec rake lint
    - name: Check syntax of Ruby files and call :syntax and :metadata_lint
      run: bundle exec rake validate
    - name: Fails if symlinks are present in directory
      run: bundle exec rake check:symlinks
    - name: Fails if .pp files present in tests folder
      run: bundle exec rake check:test_file
    - name: Fails if any ._ files are present in directory
      run: bundle exec rake check:dot_underscore
    - name: Fails if directories contain the files specified in .gitignore
      run: bundle exec rake check:git_ignore
    - name: check for trailing whitespace
      run: bundle exec rake check:trailing_whitespace
    - name: Run spec tests in parallel and clean the fixtures directory if successful
      run: bundle exec rake parallel_spec
